name: Clean Piper Docker GHCR
on:
  registry_package:

defaults:
  run:
    shell: bash

jobs:

  clean:
    runs-on: ubuntu-latest
    container: python:3.7.4-slim
    steps:
      - uses: actions/checkout@v2
      - name: Delete all except last 5
        run: |
          pip install requests==2.26.0
          python devops/github/registry.py --artifact piper --action delete-all-except-last --keep 5
