name: Piper Docker
on:
  push:
    branches: [ release/docker/* ]
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/build-push-action@v2.6.1
        with:
          file: containers/python/Dockerfile
          push: true
          tags: piper-tools/piper:${GITHUB_SHA}

  test:
    needs: build
    runs-on: ubuntu-latest
    container: ghcr.io/piper-tools/piper:${GITHUB_SHA}
    steps:
      - run: |
          cd tests/data/complexproject
          python -m piper setup
