name: Piper Package
on:
  push:
    branches: [ release/piper/* ]
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ dev ]
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:

  ##########################################
  # PYTHON
  ##########################################

  pack:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7.11'
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pack
        run: |
          cd src/piper/package
          python setup.py sdist
          cp -r dist ${{ github.workspace }}
      - name: Upload dist
        uses: actions/upload-artifact@v2
        with:
          name: piper-dist
          path: dist
          if-no-files-found: error

  test-package:
    needs: pack
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7.11'
      - name: Download dist
        uses: actions/download-artifact@v2
        with:
          name: piper-dist
          path: ${{ github.workspace }}/dist
      - name: Install piper
        run: |
          pip install dist/$( ls dist )
      - uses: actions/checkout@v2
      - name: Test the Complex Project
        run: source devops/piper/test.sh


  ##########################################
  # DOCKER
  ##########################################

  build-docker:
    needs: pack
    runs-on: ubuntu-latest
    steps:
      - name: Download dist
        uses: actions/download-artifact@v2
        with:
          name: piper-dist
          path: ${{ github.workspace }}/dist
      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v2.6.1
        with:
          build-args: |
            DIST=${{ github.workspace }}/dist
          file: containers/piper/Dockerfile
          push: true
          tags: ghcr.io/piper-tools/piper:${{ github.sha }}

  test-docker:
    needs: build-docker
    runs-on: ubuntu-latest
    container: ghcr.io/piper-tools/piper:${{ github.sha }}
    steps:
      - uses: actions/checkout@v2
      - name: Test the Complex Project
        run: source devops/piper/test.sh

  clean-docker:
    needs: build-docker
    runs-on: ubuntu-latest
    container: python:3.7.4-slim
    steps:
      - uses: actions/checkout@v2
      - name: Delete all except last 5
        env:
          REGISTRY_PAT: ${{ secrets.REGISTRY_PAT }}
        run: |
          pip install requests==2.26.0
          python devops/github/registry.py --artifact piper --action delete-all-except-last --keep 5
