name: Piperblue
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ master ]
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:

  pack:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7.11'
      - name: Install dependencies
        run: pip install requests==2.26.0
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get next tag
        id: tags
        run: echo "::set-output name=next::$( python devops/github/tags.py ${{ github.repository }} ${{ github.head_ref }} )"
      - name: "Change tag"
        run: python devops/github/replace.py src/piperblue/package/setup.py version=.+, version=\"${{ steps.tags.outputs.next }}\",
      - name: Pack
        run: |
          cd src/piperblue/package
          python setup.py sdist
          cp -r dist ${{ github.workspace }}
      - name: Upload dist
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist
          if-no-files-found: error

  test-package:
    needs: pack
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7.11'
      - name: Download dist
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: ${{ github.workspace }}/dist
      - name: Install package
        run: |
          pip install dist/$( ls dist )
      - uses: actions/checkout@v2
      - name: Test
        run: |
          pip install pytest
          source devops/piperblue/test.sh



