name: Build Piper Docker
on:
  push:
    branches: [ release/docker/* ]
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ dev ]
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v2.6.1
        with:
          file: containers/piper/Dockerfile
          push: true
          tags: ghcr.io/piper-tools/piper:${{ github.sha }}

  test:
    needs: build
    runs-on: ubuntu-latest
    container: ghcr.io/piper-tools/piper:${{ github.sha }}
    steps:
      - uses: actions/checkout@v2
      - name: Test the Complex Project
        run: |
          cd src/piper/tests/data/complexproject
          piper setup
          cd microservices/second/
          source venv-second/bin/activate
          python package/second/__init__.py
          piper clean

  clean:
    needs: build
    runs-on: ubuntu-latest
    container: python:3.7.4-slim
    steps:
      - uses: actions/checkout@v2
      - name: Delete all except last 5
        env:
          REGISTRY_PAT: ${{ secrets.REGISTRY_PAT }}
        run: |
          pip install requests==2.26.0
          python devops/github/registry.py --artifact piper --action delete-all-except-last --keep 5
